### ISSUE TITLE
Won't Install on Laravel version 11

### ISSUE THREAD

**Issue by chrisscalzo** [itbm/laravel-jetstream-disable-personal-team#1]
**When I attempted to run the command:**

composer require itbm/laravel-jetstream-disable-personal-team

**I get the following on the command line:**

$ composer require itbm/laravel-jetstream-disable-personal-team:^1.1.1
./composer.json has been updated
Running composer update itbm/laravel-jetstream-disable-personal-team
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires itbm/laravel-jetstream-disable-personal-team ^1.1.1 -> satisfiable by itbm/laravel-jetstream-disable-personal-team[1.1.1].
    - itbm/laravel-jetstream-disable-personal-team 1.1.1 requires illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.20] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by itbm** [comment]
I have bumped the versions to allow installation with Laravel 11.x

**Comment by chrisscalzo** [comment]
Thank you. It works now. Very helpful.
